List alignment
EDMdesigner/bulletprooflist pull request #7
Opened 2018-05-18 13:21 UTC by smiska

2018-05-18 14:32 UTC, gyulanemeth requested changes

2018-05-18 14:32 UTC, gyulanemeth commented on src/bulletprooflist.js
> +        var liProcessor = (function (numbered) {
you introduced an unnecessary scope here.

2018-05-18 14:32 UTC, gyulanemeth commented on src/bulletprooflist.js
> +            var bullet = ((function listElemMarker() {
I also don't understand why you need this scope here.

2018-05-18 14:32 UTC, gyulanemeth commented on src/bulletprooflist.js
> +            act.replaceWith(table);
tabs vs spaces.

2018-05-18 14:32 UTC, gyulanemeth commented on src/bulletprooflist.js
> +        var alignmentModifier = (function () {
why do you need to wrap this into a function which is executed immediately???

2018-05-18 14:32 UTC, gyulanemeth commented on src/bulletprooflist.js
> +            var equalityChecker = tableAligns.every((v, i, a) => i === 0 || v === a[i - 1] );
by the name of the variable, I would guess it's a function. Also, you use var and const... why don't you use const all the time?

2018-05-30 07:37 UTC, gyulanemeth requested changes

2018-05-30 07:37 UTC, gyulanemeth commented on src/bulletprooflist.js
> +			var alignment = alignmentProp ? "align=\"" + alignmentProp + "\"" : "";
you can add a space here, so you can remove the unnecessary one later.

2018-05-30 07:37 UTC, gyulanemeth commented on src/bulletprooflist.js
> +			var table = $("<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" " + alignment + "></table>");
here.

2018-05-30 07:37 UTC, gyulanemeth commented on src/bulletprooflist.js
> +			var equalityChecker = tableAligns.every((v, i, a) => i === 0 || v === a[i - 1] );
what about v === a[0] in the every? Also, why did you use v, i and a?

2018-07-17 12:47 UTC, smiska commented
@gyulanemeth 
please allocate time to debug sometime

2023-03-03 13:01 UTC, closed without merging